namespace SocialButterflAi.Models.LLMIntegration.OpenAi.Response
{
    public enum FinishReason
    {
        stop, //means the API returned the full chat completion generated by the model without running into any limits
        length //ran out of tokens
    }
}